// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyrmaSGS.Models;

#nullable disable

namespace SyrmaSGS.Migrations
{
    [DbContext(typeof(SyrmasgsAttendanceContext))]
    [Migration("20240702060816_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SyrmaSGS.Models.EmployeeMaster", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("CATEGORY_NAME");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DEPARTMENT_NAME");

                    b.Property<string>("DesignationName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESIGNATION_NAME");

                    b.Property<string>("Dob")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DOB");

                    b.Property<string>("Doj")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DOJ");

                    b.Property<string>("EMailId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("E-MAIL ID");

                    b.Property<string>("Employeeid")
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)")
                        .HasColumnName("EMPLOYEEID");

                    b.Property<string>("Employeename")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("EMPLOYEENAME");

                    b.Property<string>("Gender")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("GENDER");

                    b.Property<string>("ReportingManagerEMailId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("REPORTING MANAGER E-MAIL ID");

                    b.Property<double?>("ReportingManagerId")
                        .HasColumnType("float")
                        .HasColumnName("REPORTING MANAGER ID");

                    b.Property<string>("ReportingManagerName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("REPORTING MANAGER NAME");

                    b.Property<double?>("SNo")
                        .HasColumnType("float")
                        .HasColumnName("S.NO");

                    b.Property<string>("Unit")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("UNIT");

                    b.ToTable("EmployeeMaster", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
